# Generated by Django 4.0.1 on 2022-01-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salesman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('aname', models.CharField(max_length=50)),
                ('commision', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discontinue', models.IntegerField(default=0)),
            ],
        ),
    ]
